# Documentation for the serverless configuration of WebSockets
# is available here:
# https://www.serverless.com/framework/docs/providers/aws/events/websocket/

service:
  name: braidedjs-api-ws

provider:
  name: aws
  runtime: nodejs12.x
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action
  # custom routes are selected by the value of the action property in the body
  logs:
    websocket: true
  deploymentBucket:
    name: braidedjs

functions:
  connectHandler:
    handler: handler.connectHandler
    events:
      - websocket:
          route: $connect
        # authorizer: auth # reference the auth function below
        # or
        # authorizer: arn:aws:lambda:us-east-1:1234567890:function:auth
  disconnectHandler:
    handler: handler.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  helloHandler:
    handler: handler.helloHandler
    events:
      - websocket:
          route: hello
          routeResponseSelectionExpression: $default
  # auth:
  #   handler: handler.auth
