service:
  name: braidedjs-www-redirect

provider:
  name: cloudflare
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}

plugins:
  - serverless-cloudflare-workers

functions:
  api:
    name: braidedjs-www-redirect
    script: index
    events:
      - http:
          url: www.braidedjs.com/*
          method: GET
